### ISSUE TITLE
Colour Titlebar Issues

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Windows-10-Decorations#1]
Cyan Is Orange Apparently
![screenshot from 2017-05-11 17-40-26](https://cloud.githubusercontent.com/assets/11057934/25963471/f1cfc098-3670-11e7-92f8-d037ef164763.png)

**Comment by dominichayesferen** [comment]
Dark Orange is BROKEN
![screenshot from 2017-05-11 17-43-03](https://cloud.githubusercontent.com/assets/11057934/25963578/4b6a984e-3671-11e7-8515-c09a067ee2c0.png)

**Comment by dominichayesferen** [comment]
...and Yellow is more lime-coloured...

**Comment by Elbullazul** [comment]
??? will revise, but looks strange enough...
