### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Extarys** [B00merang-Project/Windows-10-Decorations#2]
Thans for all those amazing themes! I'm now a theme-whore I switch every couple of days they are all beautiful!

How can I use the Windows 10 decorations? :)
Also, any good android and sierra icon pack?

Thank you!

**Comment by Elbullazul** [comment]
you download the pack and extract the themes into ~/.themes

macOS: [la capitaine](https://github.com/keeferrourke/la-capitaine-icon-theme)

android: [paper](https://github.com/snwh/paper-icon-theme) or [numix](https://github.com/numixproject/numix-icon-theme-circle)

cheers
