### ISSUE TITLE
desktop item name shadow

### ISSUE THREAD

**Issue by AtsignSina** [B00merang-Project/Windows-10-Decorations#3]
Hey
The shadows for desktop items are shown with a not apropirate space
![Screenshot_2019-03-10_16-12-52](https://user-images.githubusercontent.com/38714950/54085145-b7677980-434f-11e9-98e9-3c86d69431de.png)

**Comment by Elbullazul** [comment]
hi,

you probably want to open an issue here instead: https://github.com/B00merang-Project/Windows-10/issues
